tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
    - redhat.java
    - richardwillis.vscode-gradle
    - vscjava.vscode-java-dependency
    - pivotal.vscode-boot-dev-pack
